name: Crawler Proxy Pool (Hour)
on:
  pull_request:
    types:
      - closed
    branches:
      - release
  schedule:
    - cron: '30 * * * *'

jobs:
  yundaili:
    name: Crawler Proxy Pool - YunDaili
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ secrets.BRANCH }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Packages
        run: pip install -r requirements.txt
      - name: Run Script
        env:
          application_id: ${{ secrets.APPLICATION_ID }}
          rest_key: ${{ secrets.REST_KEY }}
          target: 'yundaili'
          protocol: 'HTTP'
        run: python main_crawler.py
  yundaili_free:
    name: Crawler Proxy Pool - YunDailiFree
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ secrets.BRANCH }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Packages
        run: pip install -r requirements.txt
      - name: Run Script
        env:
          application_id: ${{ secrets.APPLICATION_ID }}
          rest_key: ${{ secrets.REST_KEY }}
          target: 'yundaili_free'
          protocol: 'HTTP'
        run: python main_crawler.py
  jiangxianli:
    name: Crawler Proxy Pool - Jiangxianli
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ secrets.BRANCH }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Packages
        run: pip install -r requirements.txt
      - name: Run Script
        env:
          application_id: ${{ secrets.APPLICATION_ID }}
          rest_key: ${{ secrets.REST_KEY }}
          target: 'jiangxianli'
          protocol: 'HTTPS'
        run: python main_crawler.py
