name: Verify Proxy Pool
on:
  pull_request:
    types:
      - closed
    branches:
      - release
  schedule:
    - cron: '30 * * * *'

jobs:
  run:
    name: Verify Proxy Pool
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ secrets.BRANCH }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Packages
        run: pip install -r requirements.txt
      - name: Run Script
        env:
          application_id: ${{ secrets.APPLICATION_ID }}
          rest_key: ${{ secrets.REST_KEY }}
        run: python main_verify.py
